# Generated by Django 3.2.4 on 2021-06-24 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=25, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='NameOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=25, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='GeneralTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Outcome')], default='OUT', max_length=3)),
                ('sum_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('comment', models.CharField(default='', max_length=100, verbose_name='Комментарии')),
                ('on_delete', models.BooleanField(default=False, verbose_name='enabled')),
                ('d_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.section', verbose_name='Раздел')),
                ('id_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.category', verbose_name='Категория')),
                ('id_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.nameoperation', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Главная таблица',
                'verbose_name_plural': 'Главные таблицы',
            },
        ),
    ]
