# Generated by Django 3.2.4 on 2021-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20210624_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='nameoperation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
