# Generated by Django 3.2.4 on 2021-06-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210626_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltable',
            name='d_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec', to='main_page.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='main_page.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nam', to='main_page.nameoperation', verbose_name='Name'),
        ),
    ]
