# Generated by Django 3.2.4 on 2021-07-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210627_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaltable',
            old_name='d_section',
            new_name='id_section',
        ),
    ]
