# Generated by Django 3.2.4 on 2021-07-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_rename_d_section_generaltable_id_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_sec', to='main_page.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='generaltable',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Belarussian ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUR', 'RUssian ruble'), ('PLZ', 'Zloty')], default='BYN', max_length=3),
        ),
        migrations.AddField(
            model_name='nameoperation',
            name='to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_cat', to='main_page.category', verbose_name='Category'),
        ),
    ]
