# Generated by Django 3.2.4 on 2021-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20210702_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled_category',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='nameoperation',
            name='enabled_name',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='section',
            name='enabled_section',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUR', 'RUR'), ('PLZ', 'PLZ')], default='BYN', max_length=3),
        ),
    ]
