# Generated by Django 3.2.4 on 2021-07-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_auto_20210705_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='to_section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_sec', to='main_page.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main_page.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nam', to='main_page.nameoperation', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='main_page.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='nameoperation',
            name='to_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_cat', to='main_page.category', verbose_name='Category'),
        ),
    ]
