# Generated by Django 3.2.4 on 2021-09-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20210721_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltable',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Byn'), ('USD', 'Usd'), ('EUR', 'Eur'), ('RUR', 'Rur'), ('PLZ', 'Plz')], default='BYN', max_length=3),
        ),
    ]
