# Generated by Django 3.2.4 on 2021-11-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_generaltable_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameoperation',
            options={'verbose_name': 'Name Operation', 'verbose_name_plural': 'Names Operation'},
        ),
        migrations.RemoveField(
            model_name='nameoperation',
            name='name',
        ),
        migrations.AddField(
            model_name='nameoperation',
            name='name_operation',
            field=models.CharField(default='Default Name Operation', max_length=50, verbose_name='Name Operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nam', to='main_page.nameoperation', verbose_name='Name Operation'),
        ),
    ]
