# Generated by Django 3.2.4 on 2021-11-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0019_generaltable_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_user_from_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL, verbose_name='User_category'),
        ),
        migrations.AddField(
            model_name='nameoperation',
            name='id_user_from_name_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name_operation', to=settings.AUTH_USER_MODEL, verbose_name='User_name_operation'),
        ),
        migrations.AddField(
            model_name='section',
            name='id_user_from_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_section', to=settings.AUTH_USER_MODEL, verbose_name='User_section'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main_page.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nam', to='main_page.nameoperation', verbose_name='Name Operation'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='main_page.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='generaltable',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
