version: "3.3"

services:
  db:
    build: 
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db





